name: ransomwatch

on:
  schedule:
    - cron: '7 */2 * * *'
  workflow_dispatch:

# to consider: the use of action jobs to breakout each task
# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

jobs:
  torsocks-job:
    runs-on: ubuntu-latest
    timeout-minutes: 170
    environment: CI
    services:
      torproxy:
        image: ghcr.io/jmousqueton/ransomwatch/torproxy:latest
        ports:
        - 9050:9050
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
          playwright install
      - name: run scraper
        run: |
          python3 ransomwatch.py scrape
      - name: run parser
        env: 
          # DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MS_TEAMS_WEBHOOK: ${{ secrets.MS_TEAMS_WEBHOOK }}
          # TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          # TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          # TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          # TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        run: |
          python3 ransomwatch.py parse
      - name: generate markdown & graphs for docsify
        run: |
          python3 ransomwatch.py markdown
      - name: save changes
        # git config --global user.email "jmousqueton@users.noreply.github.com"
        # git config --global user.name "Julien"
        run: |  
          # git config user.name github-actions
          # git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "Updated by Crontab on $DATE"  --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" || echo "no changes to commit" 
          git push
g